### ISSUE TITLE
Error with -Inf rewards

### ISSUE THREAD

**Issue by zsunberg** [JuliaPOMDP/POMCP.jl#19]
As @juliohm found, If rewards of -Inf are used, solver.jl line 137 will end up with NaN and there will eventually be hard-to-diagnose errors.

Behavior for this needs to be defined and tested.

**Comment by mykelk** [comment]
We have a couple options:
1. Replace line 137 with something like
```julia
if best_node.V != -Inf
    best_node.V += (R-best_node.V)/best_node.N
end    
```
2. After 137, add `@assert !isnan(best_node.V)`

**Comment by zsunberg** [comment]
Yeah, I think we should support -Inf so the first one seems best. Positive inf will throw a warning because that makes little sense. If they return a NaN reward, they will have to catch that themselves.
